# Font configuration
[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaCove Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaCove Nerd Font", style = "Italic" }
bold_italic = { family = "CaskaydiaCove Nerd Font", style = "Bold Italic" }
size = 12.0

# Colors (Catppuccin Mocha)
[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

# Window settings
[window]
# Set window dimensions for 80% of screen size (calculated for 1920x1080)
dimensions = { columns = 219, lines = 57 }
padding = { x = 10, y = 10 }
decorations = "None"
startup_mode = "Windowed"
opacity = 0.9
dynamic_padding = false



# Performance
[scrolling]
history = 40000
multiplier = 3

# Key bindings
[keyboard]
bindings = [
    { key = "V", mods = "Control|Shift", action = "Paste" },
    { key = "C", mods = "Control|Shift", action = "Copy" },
    # Toggle vi mode
    { key = "Space", mods = "Control|Shift", action = "ToggleViMode" },
    # Vi mode navigation
    { key = "Escape", mode = "Vi", action = "ClearSelection" },
    { key = "I", mode = "Vi", action = "ToggleViMode" },
    { key = "Y", mode = "Vi", action = "Copy" },
    { key = "V", mode = "Vi", action = "ToggleNormalSelection" },
    { key = "V", mods = "Shift", mode = "Vi", action = "ToggleLineSelection" },
    { key = "V", mods = "Control", mode = "Vi", action = "ToggleBlockSelection" },
    # Fullscreen toggle
    { key = "F11", action = "ToggleFullscreen" },
    { key = "Return", mods = "Alt", action = "ToggleFullscreen" },
]
