version : '3'



tasks:

 hm:switch:
  desc: Switch to the home directory
  cmd : home-manager switch --flake .#ab_dullah 
 
 nix:clean:
  desc: Clean up the Nix store
  cmd : nix-collect-garbage --delete-older-than 30d

 nix:update:
  desc: Update Nix packages
  cmd : nix-env -u '*'