version : '3'



tasks:

 hm:switch:
  desc: Switch to the home directory
  cmd : home-manager switch --flake .#ab_dullah 
 
 nix:clean:
  desc: Clean up the Nix store
  cmd : nix-collect-garbage -d

 nix:update:
  desc: Update Nix packages
  cmd : nix-env -u '*'

 npm:set-prefix:
  desc: Set npm prefix to local, to avoid permission issues 
  cmd : npm config set prefix ~/.npm-global